Update README.md
DEBUG_TB_PANELS in flask-debugtoolbar==0.11.0 is tuple and not a list.  
Adding it this way: `app.config['DEBUG_TB_PANELS'].append('flask_debugtb_elasticsearch.panel.ElasticsearchDebugPanel')` is causing error `AttributeError: 'tuple' object has no attribute 'append'`  
The easy solution is to convert DEBUG_TB_PANELS tuple to list.